# -*- coding: utf-8 -*-
"""Configuration_Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3my4DXkJ3-lenRCM0wsI6P2cEK49rBq

####Core Configuration Module
"""

"""
Loads environment variables and provides application configuration.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class Config:
    """Application configuration class."""

    # Project root directory
    BASE_DIR = Path(__file__).resolve().parent.parent

    # Google Drive Configuration
    GOOGLE_CREDENTIALS_FILE = os.getenv('GOOGLE_CREDENTIALS_FILE', 'credentials.json')
    GOOGLE_TOKEN_FILE = os.getenv('GOOGLE_TOKEN_FILE', 'token.json')
    GOOGLE_SCOPES = os.getenv('GOOGLE_SCOPES', 'https://www.googleapis.com/auth/drive.readonly').split(',')

    # Elasticsearch Configuration
    ELASTICSEARCH_HOST = os.getenv('ELASTICSEARCH_HOST', 'localhost')
    ELASTICSEARCH_PORT = int(os.getenv('ELASTICSEARCH_PORT', 9200))
    ELASTICSEARCH_INDEX = os.getenv('ELASTICSEARCH_INDEX', 'gdrive_documents')
    ELASTICSEARCH_USER = os.getenv('ELASTICSEARCH_USER', 'elastic')
    ELASTICSEARCH_PASSWORD = os.getenv('ELASTICSEARCH_PASSWORD', 'changeme')

    # Flask Configuration
    FLASK_HOST = os.getenv('FLASK_HOST', '0.0.0.0')
    FLASK_PORT = int(os.getenv('FLASK_PORT', 5000))
    FLASK_DEBUG = os.getenv('FLASK_DEBUG', 'False').lower() == 'true'

    # Sync Configuration
    SYNC_INTERVAL_MINUTES = int(os.getenv('SYNC_INTERVAL_MINUTES', 30))
    MAX_FILE_SIZE_MB = int(os.getenv('MAX_FILE_SIZE_MB', 100))
    MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

    # Logging Configuration
    LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
    LOG_FILE = os.getenv('LOG_FILE', 'logs/app.log')

    # Supported File Types
    SUPPORTED_EXTENSIONS = os.getenv('SUPPORTED_EXTENSIONS', '.txt,.csv,.pdf,.png,.jpg,.jpeg').split(',')

    # OCR Configuration
    TESSERACT_CMD = os.getenv('TESSERACT_CMD', '/usr/bin/tesseract')
    OCR_ENABLED = os.getenv('OCR_ENABLED', 'True').lower() == 'true'

    # Apache Tika Configuration
    TIKA_SERVER_URL = os.getenv('TIKA_SERVER_URL', 'http://localhost:9998')
    TIKA_ENABLED = os.getenv('TIKA_ENABLED', 'False').lower() == 'true'

    @classmethod
    def get_elasticsearch_url(cls):
        """Get Elasticsearch connection URL."""
        return f"http://{cls.ELASTICSEARCH_HOST}:{cls.ELASTICSEARCH_PORT}"

    @classmethod
    def get_credentials_path(cls):
        """Get absolute path to Google credentials file."""
        return cls.BASE_DIR / cls.GOOGLE_CREDENTIALS_FILE

    @classmethod
    def get_token_path(cls):
        """Get absolute path to Google token file."""
        return cls.BASE_DIR / cls.GOOGLE_TOKEN_FILE

    @classmethod
    def validate_config(cls):
        """Validate critical configuration."""
        errors = []

        if not cls.get_credentials_path().exists():
            errors.append(f"Google credentials file not found: {cls.get_credentials_path()}")

        if not cls.ELASTICSEARCH_HOST:
            errors.append("Elasticsearch host not configured")

        return errors

# Create config instance
config = Config()