# -*- coding: utf-8 -*-
"""Gdrive_client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3my4DXkJ3-lenRCM0wsI6P2cEK49rBq

#### Google Drive Client
"""

"""
Google Drive Client for fetching files and their content.
Handles authentication and file operations.
"""

import io
import os
from typing import List, Dict, Optional
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
from googleapiclient.errors import HttpError

from config import config
from src.utils import setup_logger

logger = setup_logger(__name__, config.LOG_FILE, config.LOG_LEVEL)


class GoogleDriveClient:
    """Client for interacting with Google Drive API."""

    def __init__(self):
        """Initialize Google Drive client."""
        self.service = None
        self.credentials = None
        self._authenticate()

    def _authenticate(self):
        """Authenticate with Google Drive API."""
        creds = None
        token_path = config.get_token_path()
        credentials_path = config.get_credentials_path()

        # Load existing token
        if token_path.exists():
            try:
                creds = Credentials.from_authorized_user_file(str(token_path), config.GOOGLE_SCOPES)
                logger.info("Loaded existing credentials from token file")
            except Exception as e:
                logger.warning(f"Failed to load token file: {e}")

        # Refresh or get new credentials
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                try:
                    creds.refresh(Request())
                    logger.info("Refreshed expired credentials")
                except Exception as e:
                    logger.error(f"Failed to refresh credentials: {e}")
                    creds = None

            if not creds:
                if not credentials_path.exists():
                    raise FileNotFoundError(
                        f"Credentials file not found: {credentials_path}. "
                        "Please download credentials.json from Google Cloud Console."
                    )

                flow = InstalledAppFlow.from_client_secrets_file(
                    str(credentials_path), config.GOOGLE_SCOPES
                )
                creds = flow.run_local_server(port=0)
                logger.info("Obtained new credentials via OAuth flow")

            # Save credentials
            token_path.parent.mkdir(parents=True, exist_ok=True)
            with open(token_path, 'w') as token:
                token.write(creds.to_json())
            logger.info(f"Saved credentials to {token_path}")

        self.credentials = creds
        self.service = build('drive', 'v3', credentials=creds)
        logger.info("Google Drive client authenticated successfully")

    def list_files(self, page_size: int = 1000, query: Optional[str] = None) -> List[Dict]:
        """
        List all files from Google Drive.

        Args:
            page_size: Number of files per page
            query: Custom query filter (optional)

        Returns:
            List of file metadata dictionaries
        """
        try:
            files = []
            page_token = None

            # Build query for supported file types
            if not query:
                mime_queries = []
                extension_queries = []

                for ext in config.SUPPORTED_EXTENSIONS:
                    extension_queries.append(f"name contains '{ext}'")

                query = f"({' or '.join(extension_queries)}) and trashed=false"

            logger.info(f"Listing files with query: {query}")

            while True:
                results = self.service.files().list(
                    pageSize=page_size,
                    pageToken=page_token,
                    q=query,
                    fields="nextPageToken, files(id, name, mimeType, size, modifiedTime, webViewLink, webContentLink)",
                    supportsAllDrives=True,
                    includeItemsFromAllDrives=True
                ).execute()

                items = results.get('files', [])
                files.extend(items)

                page_token = results.get('nextPageToken')
                if not page_token:
                    break

            logger.info(f"Found {len(files)} files in Google Drive")
            return files

        except HttpError as error:
            logger.error(f"Failed to list files: {error}")
            raise

    def download_file(self, file_id: str) -> bytes:
        """
        Download file content from Google Drive.

        Args:
            file_id: Google Drive file ID

        Returns:
            File content as bytes
        """
        try:
            request = self.service.files().get_media(fileId=file_id)
            file_buffer = io.BytesIO()
            downloader = MediaIoBaseDownload(file_buffer, request)

            done = False
            while not done:
                status, done = downloader.next_chunk()
                if status:
                    logger.debug(f"Download progress: {int(status.progress() * 100)}%")

            file_buffer.seek(0)
            content = file_buffer.read()
            logger.debug(f"Downloaded file {file_id}, size: {len(content)} bytes")
            return content

        except HttpError as error:
            logger.error(f"Failed to download file {file_id}: {error}")
            raise

    def get_file_metadata(self, file_id: str) -> Dict:
        """
        Get metadata for a specific file.

        Args:
            file_id: Google Drive file ID

        Returns:
            File metadata dictionary
        """
        try:
            file_metadata = self.service.files().get(
                fileId=file_id,
                fields="id, name, mimeType, size, modifiedTime, webViewLink, webContentLink",
                supportsAllDrives=True
            ).execute()

            return file_metadata

        except HttpError as error:
            logger.error(f"Failed to get metadata for file {file_id}: {error}")
            raise

    def check_file_exists(self, file_id: str) -> bool:
        """
        Check if a file exists in Google Drive.

        Args:
            file_id: Google Drive file ID

        Returns:
            True if file exists, False otherwise
        """
        try:
            self.service.files().get(
                fileId=file_id,
                fields="id",
                supportsAllDrives=True
            ).execute()
            return True
        except HttpError:
            return False