# -*- coding: utf-8 -*-
"""sync_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3my4DXkJ3-lenRCM0wsI6P2cEK49rBq

#### Sync Service
"""

"""
Sync service for synchronizing Google Drive files with Elasticsearch index.
"""

from typing import Dict, List
from pathlib import Path
from datetime import datetime

from config import config
from src.storage import GoogleDriveClient, TextExtractor
from src.indexer.index_manager import IndexManager
from src.utils import setup_logger

logger = setup_logger(__name__, config.LOG_FILE, config.LOG_LEVEL)


class SyncService:
    """Service for synchronizing files from Google Drive to Elasticsearch."""

    def __init__(self):
        """Initialize sync service."""
        self.gdrive_client = GoogleDriveClient()
        self.index_manager = IndexManager()
        self.text_extractor = TextExtractor()

        # Ensure index exists
        self.index_manager.create_index()

    def sync_all_files(self) -> Dict:
        """
        Sync all files from Google Drive to Elasticsearch.

        Returns:
            Dictionary with sync statistics
        """
        logger.info("Starting full sync of Google Drive files")
        start_time = datetime.now()

        stats = {
            "total_files": 0,
            "indexed": 0,
            "updated": 0,
            "failed": 0,
            "skipped": 0,
            "deleted": 0,
            "duration_seconds": 0
        }

        try:
            # Get all files from Google Drive
            gdrive_files = self.gdrive_client.list_files()
            stats["total_files"] = len(gdrive_files)

            # Get currently indexed file IDs
            indexed_file_ids = set(self.index_manager.get_all_indexed_file_ids())
            gdrive_file_ids = set(file['id'] for file in gdrive_files)

            # Find files to delete (in index but not in Google Drive)
            files_to_delete = indexed_file_ids - gdrive_file_ids
            for file_id in files_to_delete:
                if self.index_manager.delete_document(file_id):
                    stats["deleted"] += 1

            # Process each file
            for file_metadata in gdrive_files:
                result = self._process_file(file_metadata)

                if result == "indexed":
                    stats["indexed"] += 1
                elif result == "updated":
                    stats["updated"] += 1
                elif result == "failed":
                    stats["failed"] += 1
                elif result == "skipped":
                    stats["skipped"] += 1

            # Calculate duration
            end_time = datetime.now()
            stats["duration_seconds"] = (end_time - start_time).total_seconds()

            logger.info(f"Sync completed: {stats}")
            return stats

        except Exception as e:
            logger.error(f"Sync failed: {e}")
            stats["error"] = str(e)
            return stats

    def sync_file(self, file_id: str) -> Dict:
        """
        Sync a single file by ID.

        Args:
            file_id: Google Drive file ID

        Returns:
            Dictionary with sync result
        """
        try:
            # Check if file exists in Google Drive
            if not self.gdrive_client.check_file_exists(file_id):
                # File doesn't exist, delete from index
                self.index_manager.delete_document(file_id)
                return {
                    "status": "deleted",
                    "message": "File not found in Google Drive, removed from index"
                }

            # Get file metadata
            file_metadata = self.gdrive_client.get_file_metadata(file_id)

            # Process file
            result = self._process_file(file_metadata)

            return {
                "status": result,
                "file_name": file_metadata.get("name", ""),
                "file_id": file_id
            }

        except Exception as e:
            logger.error(f"Failed to sync file {file_id}: {e}")
            return {
                "status": "failed",
                "error": str(e)
            }

    def _process_file(self, file_metadata: Dict) -> str:
        """
        Process a single file: download, extract text, and index.

        Args:
            file_metadata: File metadata from Google Drive

        Returns:
            Processing result status
        """
        file_id = file_metadata['id']
        file_name = file_metadata['name']
        file_size = int(file_metadata.get('size', 0))

        try:
            # Check file extension
            extension = Path(file_name).suffix.lower()
            if extension not in config.SUPPORTED_EXTENSIONS:
                logger.debug(f"Skipping unsupported file type: {file_name}")
                return "skipped"

            # Check file size
            if file_size > config.MAX_FILE_SIZE_BYTES:
                logger.warning(f"Skipping large file: {file_name} ({file_size} bytes)")
                return "skipped"

            # Check if already indexed (basic check)
            is_indexed = self.index_manager.document_exists(file_id)

            # Download file content
            logger.info(f"Processing file: {file_name} (ID: {file_id})")
            content_bytes = self.gdrive_client.download_file(file_id)

            # Extract text
            extracted_text = self.text_extractor.extract(content_bytes, file_name)

            if not extracted_text or len(extracted_text.strip()) == 0:
                logger.warning(f"No text extracted from {file_name}")
                extracted_text = ""

            # Index document
            success = self.index_manager.index_document(
                file_id=file_id,
                file_name=file_name,
                content=extracted_text,
                metadata=file_metadata
            )

            if success:
                return "updated" if is_indexed else "indexed"
            else:
                return "failed"

        except Exception as e:
            logger.error(f"Failed to process file {file_name}: {e}")
            return "failed"

    def cleanup_deleted_files(self) -> int:
        """
        Remove documents from index that no longer exist in Google Drive.

        Returns:
            Number of documents deleted
        """
        logger.info("Cleaning up deleted files")

        try:
            # Get all indexed file IDs
            indexed_file_ids = self.index_manager.get_all_indexed_file_ids()

            deleted_count = 0
            for file_id in indexed_file_ids:
                # Check if file still exists in Google Drive
                if not self.gdrive_client.check_file_exists(file_id):
                    if self.index_manager.delete_document(file_id):
                        deleted_count += 1

            logger.info(f"Cleaned up {deleted_count} deleted files")
            return deleted_count

        except Exception as e:
            logger.error(f"Cleanup failed: {e}")
            return 0