# -*- coding: utf-8 -*-
"""text_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3my4DXkJ3-lenRCM0wsI6P2cEK49rBq

#### Text Extraction Module
"""

"""
Text extraction module for different file types.
Supports CSV, TXT, PDF, and images (with OCR).
"""

import io
import csv
from typing import Optional
from pathlib import Path

import chardet
from PIL import Image
import pytesseract
from PyPDF2 import PdfReader

from config import config
from src.utils import setup_logger

logger = setup_logger(__name__, config.LOG_FILE, config.LOG_LEVEL)

# Configure Tesseract
if config.OCR_ENABLED and config.TESSERACT_CMD:
    pytesseract.pytesseract.tesseract_cmd = config.TESSERACT_CMD


class TextExtractor:
    """Extract text content from various file formats."""

    @staticmethod
    def detect_encoding(content: bytes) -> str:
        """
        Detect the encoding of file content.

        Args:
            content: File content as bytes

        Returns:
            Detected encoding string
        """
        result = chardet.detect(content)
        encoding = result.get('encoding', 'utf-8')
        confidence = result.get('confidence', 0)

        logger.debug(f"Detected encoding: {encoding} (confidence: {confidence:.2f})")
        return encoding or 'utf-8'

    @staticmethod
    def extract_from_txt(content: bytes) -> str:
        """
        Extract text from TXT file.

        Args:
            content: File content as bytes

        Returns:
            Extracted text
        """
        try:
            # Try UTF-8 first
            try:
                return content.decode('utf-8')
            except UnicodeDecodeError:
                # Detect and use appropriate encoding
                encoding = TextExtractor.detect_encoding(content)
                return content.decode(encoding, errors='replace')
        except Exception as e:
            logger.error(f"Failed to extract text from TXT: {e}")
            return ""

    @staticmethod
    def extract_from_csv(content: bytes) -> str:
        """
        Extract text from CSV file.

        Args:
            content: File content as bytes

        Returns:
            Extracted text (all cells concatenated)
        """
        try:
            # Decode content
            try:
                text_content = content.decode('utf-8')
            except UnicodeDecodeError:
                encoding = TextExtractor.detect_encoding(content)
                text_content = content.decode(encoding, errors='replace')

            # Parse CSV
            csv_reader = csv.reader(io.StringIO(text_content))
            rows = []
            for row in csv_reader:
                rows.append(' '.join(row))

            return '\n'.join(rows)
        except Exception as e:
            logger.error(f"Failed to extract text from CSV: {e}")
            return ""

    @staticmethod
    def extract_from_pdf(content: bytes) -> str:
        """
        Extract text from PDF file using PyPDF2.

        Args:
            content: File content as bytes

        Returns:
            Extracted text
        """
        try:
            pdf_file = io.BytesIO(content)
            pdf_reader = PdfReader(pdf_file)

            text_parts = []
            for page_num, page in enumerate(pdf_reader.pages):
                try:
                    text = page.extract_text()
                    if text:
                        text_parts.append(text)
                except Exception as e:
                    logger.warning(f"Failed to extract text from PDF page {page_num}: {e}")

            extracted_text = '\n'.join(text_parts)
            logger.debug(f"Extracted {len(extracted_text)} characters from PDF")
            return extracted_text
        except Exception as e:
            logger.error(f"Failed to extract text from PDF: {e}")

            # Try Apache Tika if enabled
            if config.TIKA_ENABLED:
                try:
                    return TextExtractor.extract_with_tika(content, 'application/pdf')
                except Exception as tika_error:
                    logger.error(f"Tika extraction also failed: {tika_error}")

            return ""

    @staticmethod
    def extract_from_image(content: bytes) -> str:
        """
        Extract text from image using OCR (Tesseract).

        Args:
            content: File content as bytes

        Returns:
            Extracted text
        """
        if not config.OCR_ENABLED:
            logger.warning("OCR is disabled in configuration")
            return ""

        try:
            image = Image.open(io.BytesIO(content))
            text = pytesseract.image_to_string(image)
            logger.debug(f"Extracted {len(text)} characters from image using OCR")
            return text
        except Exception as e:
            logger.error(f"Failed to extract text from image: {e}")

            # Try Apache Tika if enabled
            if config.TIKA_ENABLED:
                try:
                    return TextExtractor.extract_with_tika(content, 'image/*')
                except Exception as tika_error:
                    logger.error(f"Tika extraction also failed: {tika_error}")

            return ""

    @staticmethod
    def extract_with_tika(content: bytes, mime_type: str) -> str:
        """
        Extract text using Apache Tika server.

        Args:
            content: File content as bytes
            mime_type: MIME type of the file

        Returns:
            Extracted text
        """
        try:
            import requests

            headers = {
                'Content-Type': mime_type,
                'Accept': 'text/plain'
            }

            response = requests.put(
                f"{config.TIKA_SERVER_URL}/tika",
                data=content,
                headers=headers,
                timeout=30
            )
            response.raise_for_status()

            text = response.text
            logger.debug(f"Extracted {len(text)} characters using Tika")
            return text
        except Exception as e:
            logger.error(f"Failed to extract text with Tika: {e}")
            return ""

    @staticmethod
    def extract(content: bytes, filename: str) -> str:
        """
        Extract text from file based on extension.

        Args:
            content: File content as bytes
            filename: Name of the file

        Returns:
            Extracted text
        """
        extension = Path(filename).suffix.lower()

        logger.info(f"Extracting text from {filename} (type: {extension})")

        if extension == '.txt':
            return TextExtractor.extract_from_txt(content)
        elif extension == '.csv':
            return TextExtractor.extract_from_csv(content)
        elif extension == '.pdf':
            return TextExtractor.extract_from_pdf(content)
        elif extension in ['.png', '.jpg', '.jpeg']:
            return TextExtractor.extract_from_image(content)
        else:
            logger.warning(f"Unsupported file type: {extension}")
            return ""